name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        yarn install
        yarn run zip

    - name: Get version
      run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"
      id: version

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./compiled/dhis2_deprecated_authorities.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
